services:
  app:
    container_name: "backcontainer"
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=jdbc:postgresql://dpg-cv531p8gph6c73anho50-a.frankfurt-postgres.render.com/pokedex_h9i2
      - DATABASE_USERNAME=pokedex_h9i2_user
      - DATABASE_PASSWORD=J5ExFsI3U2GqrQl3EQ07uafxIxyXNTt3
      - DATABASE_DRIVER=com.mysql.cj.jdbc.Driver
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: "db"
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "pokedex"
      POSTGRES_USER: "pokedex_h9i2_user"
      POSTGRES_PASSWORD: "J5ExFsI3U2GqrQl3EQ07uafxIxyXNTt3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pokedex_h9i2_user"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  db-data:
