services:
  app:
    container_name: "backcontainer"
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://db:3306/pokedex
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_DRIVER=com.mysql.cj.jdbc.Driver
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: "db"
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: "pokedex"
      MYSQL_USER: "ale"
      MYSQL_PASSWORD: "ale"
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  db-data: